local ns = SiftTest.ns
local F = require("fixtures")
local E = ns.Eligibility
local W = ns.Data.WEAPON

describe("Eligibility.Check armor", function()
  it("rejects plate on a mage", function()
    local ok, why = E.Check(F.item({ subclassID = 4 }), F.char({ classID = 8 }), ns.Data.specs[63])
    expect(ok).toBe(false)
    expect(why).toBe("armor")
  end)

  it("accepts plate on a warrior", function()
    local ok = E.Check(F.item({ subclassID = 4 }), F.char({ classID = 1 }), ns.Data.specs[72])
    expect(ok).toBe(true)
  end)

  it("ignores armor type for cloaks, necks, rings and trinkets", function()
    local cloak = F.item({ equipLoc = "INVTYPE_CLOAK", subclassID = 1 })
    expect(E.Check(cloak, F.char({ classID = 1 }), ns.Data.specs[72])).toBe(true)
    expect(E.Check(F.ring(), F.char({ classID = 1 }), ns.Data.specs[72])).toBe(true)
  end)

  it("only lets shield classes take shields", function()
    local shield = F.item({ equipLoc = "INVTYPE_SHIELD", subclassID = 6, stats = { STAMINA = 100, CRIT = 5 }, flex = { value = 50, STRENGTH = true, INTELLECT = true } })
    expect(E.Check(shield, F.char({ classID = 1 }), ns.Data.specs[73])).toBe(true)
    local ok, why = E.Check(shield, F.char({ classID = 4 }), ns.Data.specs[260])
    expect(ok).toBe(false)
    expect(why).toBe("shield")
  end)
end)

describe("Eligibility.Check primary stat", function()
  it("rejects a fixed-intellect trinket on a warrior", function()
    local ok, why = E.Check(F.trinket({ stats = { INTELLECT = 900, CRIT = 100 } }), F.char({ classID = 1 }), ns.Data.specs[72])
    expect(ok).toBe(false)
    expect(why).toBe("primary")
  end)

  it("accepts a strength trinket on a warrior", function()
    expect(E.Check(F.trinket(), F.char({ classID = 1 }), ns.Data.specs[72])).toBe(true)
  end)

  it("rejects a flex item that cannot become the spec primary", function()
    local ok, why = E.Check(F.item({ flex = { value = 100, AGILITY = true, INTELLECT = true } }), F.char({ classID = 1 }), ns.Data.specs[72])
    expect(ok).toBe(false)
    expect(why).toBe("primary")
  end)

  it("rejects items above the character level", function()
    local ok, why = E.Check(F.item({ reqLevel = 80 }), F.char({ level = 79 }), ns.Data.specs[72])
    expect(ok).toBe(false)
    expect(why).toBe("level")
  end)
end)

describe("Eligibility.Check weapons", function()
  it("rejects a wand on a warrior and accepts it on a mage", function()
    local wand = F.weapon({ equipLoc = "INVTYPE_RANGEDRIGHT", subclassID = W.WAND, stats = { INTELLECT = 500 } })
    local ok, why = E.Check(wand, F.char({ classID = 1 }), ns.Data.specs[72])
    expect(ok).toBe(false)
    expect(why).toBe("weapon")
    -- Wands sit in the main hand for casters, so the model check must pass.
    local ok2 = E.Check(F.weapon({ equipLoc = "INVTYPE_WEAPONMAINHAND", subclassID = W.WAND, stats = { INTELLECT = 500 } }), F.char({ classID = 8 }), ns.Data.specs[63])
    expect(ok2).toBe(true)
  end)

  it("rejects a two-hander for a shield spec", function()
    local twoH = F.weapon({ equipLoc = "INVTYPE_2HWEAPON", subclassID = W.SWORD2H })
    local ok, why = E.Check(twoH, F.char({ classID = 1 }), ns.Data.specs[73])
    expect(ok).toBe(false)
    expect(why).toBe("model")
  end)

  it("accepts a two-hander for Fury via twoHandOK and for Arms", function()
    local twoH = F.weapon({ equipLoc = "INVTYPE_2HWEAPON", subclassID = W.SWORD2H })
    expect(E.Check(twoH, F.char({ classID = 1 }), ns.Data.specs[72])).toBe(true)
    expect(E.Check(twoH, F.char({ classID = 1 }), ns.Data.specs[71])).toBe(true)
  end)

  it("rejects a one-hander for Arms", function()
    local ok, why = E.Check(F.weapon(), F.char({ classID = 1 }), ns.Data.specs[71])
    expect(ok).toBe(false)
    expect(why).toBe("model")
  end)

  it("only lets hunters score bows and rejects melee for ranged specs", function()
    local bow = F.weapon({ equipLoc = "INVTYPE_RANGEDRIGHT", subclassID = W.BOW, stats = { AGILITY = 500, DPS = 900 } })
    expect(E.Check(bow, F.char({ classID = 3 }), ns.Data.specs[253])).toBe(true)
    local ok, why = E.Check(bow, F.char({ classID = 1 }), ns.Data.specs[72])
    expect(ok).toBe(false)
    expect(why).toBe("weapon")
    local ok2, why2 = E.Check(F.weapon({ subclassID = W.AXE1H, stats = { AGILITY = 500, DPS = 900 } }), F.char({ classID = 3 }), ns.Data.specs[253])
    expect(ok2).toBe(false)
    expect(why2).toBe("model")
  end)

  it("lets casters take a staff or a main hand but not an off-hand weapon", function()
    local staff = F.weapon({ equipLoc = "INVTYPE_2HWEAPON", subclassID = W.STAFF, stats = { INTELLECT = 900 } })
    expect(E.Check(staff, F.char({ classID = 8 }), ns.Data.specs[63])).toBe(true)
    local oh = F.weapon({ equipLoc = "INVTYPE_WEAPONOFFHAND", subclassID = W.DAGGER, stats = { INTELLECT = 900 } })
    local ok, why = E.Check(oh, F.char({ classID = 8 }), ns.Data.specs[63])
    expect(ok).toBe(false)
    expect(why).toBe("model")
  end)
end)
