local ns = SiftTest.ns
local P = ns.PawnString

describe("PawnString.Parse", function()
  it("parses a Raidbots-style string", function()
    local r = P.Parse('( Pawn: v1: "Raidbots-Fury": Class=Warrior, Spec=Fury, Strength=1.00, CritRating=0.55, HasteRating=0.61, MasteryRating=0.58, Versatility=0.50 )')
    expect(r.name).toBe("Raidbots-Fury")
    expect(r.class).toBe("Warrior")
    expect(r.spec).toBe("Fury")
    expect(r.classID).toBe(1)
    expect(r.specID).toBe(72)
    expect(r.weights.STRENGTH).toBe(1.0)
    expect(r.weights.HASTE).toBeCloseTo(0.61)
    expect(r.weights.VERSATILITY).toBeCloseTo(0.50)
  end)

  it("tolerates missing parentheses and extra whitespace", function()
    local r = P.Parse('Pawn:v1:"x":   Class=Mage ,Spec=Frost,Intellect=1,HasteRating=0.7')
    expect(r.classID).toBe(8)
    expect(r.specID).toBe(64)
    expect(r.weights.INTELLECT).toBe(1)
  end)

  it("accepts negative and decimal values", function()
    local r = P.Parse('( Pawn: v1: "n": Agility=1, Versatility=-0.25, Leech=0.125 )')
    expect(r.weights.VERSATILITY).toBeCloseTo(-0.25)
    expect(r.weights.LEECH).toBeCloseTo(0.125)
  end)

  it("collects unknown stat names without failing", function()
    local r = P.Parse('( Pawn: v1: "n": Class=Rogue, Spec=Outlaw, Agility=1, FooRating=3 )')
    expect(r.unknown).toContain("FooRating")
    expect(r.specID).toBe(260)
  end)

  it("matches multi-word class and spec names", function()
    local r = P.Parse('( Pawn: v1: "n": Class=DeathKnight, Spec=Blood, Strength=1 )')
    expect(r.classID).toBe(6)
    expect(r.specID).toBe(250)
    local r2 = P.Parse('( Pawn: v1: "n": Class=Hunter, Spec=BeastMastery, Agility=1 )')
    expect(r2.specID).toBe(253)
  end)

  it("rejects garbage", function()
    local r, err = P.Parse("hello world")
    expect(r).toBeNil()
    expect(err).toContain("Pawn v1")
  end)

  it("rejects a string with no recognized weights", function()
    local r, err = P.Parse('( Pawn: v1: "n": Class=Mage, Spec=Fire )')
    expect(r).toBeNil()
    expect(err).toContain("no recognized")
  end)

  it("rejects non-strings", function()
    local r = P.Parse(42)
    expect(r).toBeNil()
  end)
end)
