local ns = SiftTest.ns
local Specs = ns.Specs

local function client(id, classID, name, primaryStat, role)
  return Specs.FromClient({ id = id, classID = classID, name = name, primaryStat = primaryStat, role = role })
end

describe("Specs.FromClient", function()
  it("maps the client's primary stat and role codes", function()
    local r = client(72, 1, "Fury", 1, "DAMAGER")
    expect(r.primary).toBe("STRENGTH")
    expect(r.role).toBe("dps")
    expect(client(1480, 12, "Devourer", 4, "DAMAGER").primary).toBe("INTELLECT")
    expect(client(581, 12, "Vengeance", 2, "TANK").role).toBe("tank")
    expect(client(65, 2, "Holy", 4, "HEALER").role).toBe("heal")
  end)

  it("leaves unknown codes empty rather than guessing", function()
    local r = client(72, 1, "Fury", 3, "WEIRD")
    expect(r.primary).toBeNil()
    expect(r.role).toBeNil()
  end)

  it("rejects records without an id or class", function()
    local r, why = Specs.FromClient({ name = "x" })
    expect(r).toBeNil()
    expect(why).toBe("no id")
    local r2, why2 = Specs.FromClient({ id = 72 })
    expect(r2).toBeNil()
    expect(why2).toBe("no class")
    expect(Specs.FromClient(nil)).toBeNil()
  end)
end)

describe("Specs.Build", function()
  it("lays client primary and role over shipped model and priorities", function()
    local reg, diffs = Specs.Build({ client(72, 1, "Fury", 1, "DAMAGER") })
    local fury = reg[72]
    expect(fury.primary).toBe("STRENGTH")
    expect(fury.role).toBe("dps")
    expect(fury.model).toBe(ns.Data.MODEL.DUAL_WIELD)
    expect(#fury.priority).toBe(4)
    expect(fury.twoHandOK).toBe(true)
    expect(fury.source).toBe("client")
    expect(#diffs).toBe(0)
    expect(reg[71].source).toBe("shipped")
  end)

  it("lets the client win a disagreement and records it", function()
    local reg, diffs = Specs.Build({ client(1480, 12, "Devourer", 2, "DAMAGER") })
    expect(reg[1480].primary).toBe("AGILITY")
    expect(#diffs).toBe(1)
    expect(diffs[1].field).toBe("primary")
    expect(diffs[1].shipped).toBe("INTELLECT")
    expect(diffs[1].client).toBe("AGILITY")
    expect(ns.Data.specs[1480].primary).toBe("INTELLECT")
  end)

  it("keeps the shipped value when the client omits a field and says so", function()
    local reg = Specs.Build({ client(72, 1, "Fury", nil, nil) })
    expect(reg[72].primary).toBe("STRENGTH")
    expect(reg[72].primarySource).toBe("shipped")
    expect(reg[72].roleSource).toBe("shipped")
  end)

  it("synthesizes an unknown spec that scores armor but no weapons", function()
    local reg = Specs.Build({ client(9999, 1, "Bladestorm", 1, "DAMAGER") })
    local s = reg[9999]
    expect(s.unknown).toBe(true)
    expect(s.primary).toBe("STRENGTH")
    expect(s.model).toBeNil()
    expect(#s.priority).toBe(0)
    local char = { classID = 1, level = 80, slots = {} }
    local ok = ns.Eligibility.Check({ classID = 4, subclassID = 4, equipLoc = "INVTYPE_CHEST", stats = {}, flex = { value = 1, STRENGTH = true } }, char, s)
    expect(ok).toBe(true)
    local okW = ns.Eligibility.Check({ classID = 2, subclassID = 7, equipLoc = "INVTYPE_WEAPON", stats = { STRENGTH = 1 } }, char, s)
    expect(okW).toBe(false)
    local w = ns.Weights.FromSpec(s)
    expect(w.STRENGTH).toBe(1.0)
    expect(w.HASTE).toBeNil()
  end)

  it("rejects a record whose class contradicts the shipped class", function()
    local reg, diffs, rejected = Specs.Build({ client(72, 8, "Fury", 1, "DAMAGER") })
    expect(#rejected).toBe(1)
    expect(rejected[1].id).toBe(72)
    expect(reg[72].source).toBe("shipped")
    expect(#diffs).toBe(0)
  end)

  it("takes the client's name", function()
    local reg = Specs.Build({ client(72, 1, "Fury Renamed", 1, "DAMAGER") })
    expect(reg[72].name).toBe("Fury Renamed")
  end)
end)

describe("Specs registry", function()
  it("falls back to shipped data before anything is loaded", function()
    Specs.Reset()
    expect(Specs.Source()).toBe("shipped")
    expect(Specs.Get(72)).toBe(ns.Data.specs[72])
    expect(Specs.Get(nil)).toBeNil()
    local id = Specs.FindByName(1, "fury")
    expect(id).toBe(72)
  end)

  it("serves loaded specs and finds renamed ones by either name", function()
    local summary = Specs.Load({ client(72, 1, "Fury Renamed", 1, "DAMAGER"), client(1480, 12, "Devourer", 4, "DAMAGER") })
    expect(summary.source).toBe("client")
    expect(summary.specs).toBe(2)
    expect(summary.withPrimary).toBe(2)
    expect(summary.diffs).toBe(0)
    expect(Specs.Get(72).name).toBe("Fury Renamed")
    expect(Specs.FindByName(1, "Fury Renamed")).toBe(72)
    expect(Specs.FindByName(1, "Fury")).toBe(72)
    expect(#Specs.ForClass(12)).toBe(3)
    Specs.Reset()
  end)

  it("stays on shipped data when the client gives nothing", function()
    local summary = Specs.Load({})
    expect(summary.source).toBe("shipped")
    expect(Specs.Get(72)).toBe(ns.Data.specs[72])
    Specs.Reset()
  end)

  it("describes disagreements in words", function()
    Specs.Load({ client(1480, 12, "Devourer", 2, "TANK") })
    local lines = Specs.DescribeDiffs()
    expect(#lines).toBe(2)
    expect(lines[1]).toContain("Devourer primary: shipped Intellect, client Agility")
    expect(lines[2]).toContain("Devourer role: shipped dps, client tank")
    Specs.Reset()
  end)

  it("lets a Pawn string resolve its spec through the registry", function()
    Specs.Load({ client(72, 1, "Fury Renamed", 1, "DAMAGER") })
    local p = ns.PawnString.Parse('( Pawn: v1: "x": Class=Warrior, Spec=FuryRenamed, Strength=1 )')
    expect(p.specID).toBe(72)
    Specs.Reset()
  end)
end)
