local ns = SiftTest.ns
local Stats = ns.Stats

describe("Stats.Normalize", function()
  it("maps known tokens to canonical keys", function()
    local s = Stats.Normalize({ ITEM_MOD_STRENGTH_SHORT = 100, ITEM_MOD_CRIT_RATING_SHORT = 50, ITEM_MOD_VERSATILITY = 20 })
    expect(s).toEqual({ STRENGTH = 100, CRIT = 50, VERSATILITY = 20 })
  end)

  it("extracts an adaptive primary into flex", function()
    local s, flex = Stats.Normalize({ ITEM_MOD_AGI_STR_INT_SHORT = 900, ITEM_MOD_STAMINA_SHORT = 1200 })
    expect(s).toEqual({ STAMINA = 1200 })
    expect(flex.value).toBe(900)
    expect(flex.AGILITY).toBe(true)
    expect(flex.STRENGTH).toBe(true)
    expect(flex.INTELLECT).toBe(true)
  end)

  it("handles a two-way flex token", function()
    local _, flex = Stats.Normalize({ ITEM_MOD_AGI_INT_SHORT = 500 })
    expect(flex.AGILITY).toBe(true)
    expect(flex.INTELLECT).toBe(true)
    expect(flex.STRENGTH).toBeNil()
  end)

  it("ignores unknown tokens, zeros and non-numbers", function()
    local s, flex = Stats.Normalize({ ITEM_MOD_FOO = 5, ITEM_MOD_HASTE_RATING_SHORT = 0, ITEM_MOD_MASTERY_RATING_SHORT = "x" })
    expect(s).toEqual({})
    expect(flex).toBeNil()
  end)

  it("survives a nil table", function()
    local s, flex = Stats.Normalize(nil)
    expect(s).toEqual({})
    expect(flex).toBeNil()
  end)
end)

describe("Stats.NormalizeForArmor", function()
  it("restores the adaptive primary on leather resolved to intellect", function()
    local stats, flex = Stats.NormalizeForArmor({ INTELLECT = 800, CRIT = 100 }, nil, 4, 2, "INVTYPE_CHEST")
    expect(stats).toEqual({ CRIT = 100 })
    expect(flex.value).toBe(800)
    expect(flex.AGILITY).toBe(true)
    expect(flex.INTELLECT).toBe(true)
    expect(flex.STRENGTH).toBeNil()
  end)

  it("gives plate strength or intellect and cloth intellect only", function()
    local _, plate = Stats.NormalizeForArmor({ STRENGTH = 500 }, nil, 4, 4, "INVTYPE_LEGS")
    expect(plate.STRENGTH).toBe(true)
    expect(plate.INTELLECT).toBe(true)
    expect(plate.AGILITY).toBeNil()
    local _, cloth = Stats.NormalizeForArmor({ INTELLECT = 500 }, nil, 4, 1, "INVTYPE_ROBE")
    expect(cloth.INTELLECT).toBe(true)
    expect(cloth.AGILITY).toBeNil()
  end)

  it("keeps whatever the game resolved even if the table disagrees", function()
    local _, flex = Stats.NormalizeForArmor({ AGILITY = 500 }, nil, 4, 4, "INVTYPE_HEAD")
    expect(flex.AGILITY).toBe(true)
  end)

  it("leaves trinkets, weapons, cloaks and already-adaptive items alone", function()
    local s1, f1 = Stats.NormalizeForArmor({ INTELLECT = 500 }, nil, 4, 0, "INVTYPE_TRINKET")
    expect(s1.INTELLECT).toBe(500)
    expect(f1).toBeNil()
    local s2, f2 = Stats.NormalizeForArmor({ AGILITY = 500 }, nil, 2, 15, "INVTYPE_WEAPON")
    expect(s2.AGILITY).toBe(500)
    expect(f2).toBeNil()
    local s3, f3 = Stats.NormalizeForArmor({ STAMINA = 500 }, nil, 4, 1, "INVTYPE_CLOAK")
    expect(s3.STAMINA).toBe(500)
    expect(f3).toBeNil()
    local existing = { value = 9, AGILITY = true }
    local _, f4 = Stats.NormalizeForArmor({ INTELLECT = 500 }, existing, 4, 2, "INVTYPE_CHEST")
    expect(f4).toBe(existing)
  end)

  it("does nothing for armor with no primary stat", function()
    local s, f = Stats.NormalizeForArmor({ STAMINA = 500, CRIT = 50 }, nil, 4, 2, "INVTYPE_CHEST")
    expect(s).toEqual({ STAMINA = 500, CRIT = 50 })
    expect(f).toBeNil()
  end)
end)

describe("Stats.FixedPrimary", function()
  it("finds a fixed primary stat", function()
    expect(Stats.FixedPrimary({ INTELLECT = 10, CRIT = 5 })).toBe("INTELLECT")
  end)
  it("returns nil when there is none", function()
    expect(Stats.FixedPrimary({ CRIT = 5, STAMINA = 9 })).toBeNil()
  end)
end)

describe("Stats.ParseBonusText", function()
  local names = { Mastery = "MASTERY", Haste = "HASTE", ["Critical Strike"] = "CRIT", Versatility = "VERSATILITY", Stamina = "STAMINA" }

  it("reads a primary stat gem", function()
    local out = Stats.ParseBonusText("+32 Primary Stat", { ["Primary Stat"] = Stats.PRIMARY_GEM })
    expect(out).toEqual({ PRIMARY = 32 })
  end)

  it("reads a two-stat gem line", function()
    local out, found = Stats.ParseBonusText("+16 Mastery & +7 Haste", names)
    expect(found).toBe(true)
    expect(out).toEqual({ MASTERY = 16, HASTE = 7 })
  end)

  it("reads multi-word names, commas and thousands separators", function()
    local out = Stats.ParseBonusText("+1,200 Stamina, +9 Critical Strike and +3 Versatility", names)
    expect(out).toEqual({ STAMINA = 1200, CRIT = 9, VERSATILITY = 3 })
  end)

  it("does not match a name inside a longer word", function()
    local out, found = Stats.ParseBonusText("+5 Hastening", names)
    expect(found).toBe(false)
    expect(out).toEqual({})
  end)

  it("reports nothing for an empty socket or junk", function()
    local _, found = Stats.ParseBonusText("Prismatic Socket", names)
    expect(found).toBe(false)
    expect(select(2, Stats.ParseBonusText(nil, names))).toBe(false)
    expect(select(2, Stats.ParseBonusText("+16 Mastery", nil))).toBe(false)
  end)

  it("survives names with pattern characters", function()
    local out = Stats.ParseBonusText("+4 Crit (Rating)", { ["Crit (Rating)"] = "CRIT" })
    expect(out.CRIT).toBe(4)
  end)
end)
