-- GENERATED by tools/gen-weights on 2026-09-06. Do not edit by hand.
-- SimulationCraft 1210-01 (3f6f8c453, branch midnight), profiles/MID2, 10000 iterations per sim,
-- scale factors over dps for every role. Weights are per stat point relative
-- to the spec's primary stat. raw is dps per point, error its standard error.
-- DPS_OH is the value of a point of off-hand weapon dps for dual wielders.
local _, ns = ...

ns.WeightsData = {
  generated = "2026-09-06", simc = "1210-01", commit = "3f6f8c453beaf245fecee52e9ea3e5c5bc6ad7fb", branch = "midnight", season = "MID2", iterations = 10000,
  specs = {
    [62] = {
      profile = "MID2_Mage_Arcane", dps = 200428,
      variants = { "MID2_Mage_Arcane_Sunfury" },
      weights = { CRIT = 0.5871, HASTE = 0.5483, INTELLECT = 1.0000, MASTERY = 0.6112, VERSATILITY = 0.5578 },
      raw = { CRIT = 32.5892, HASTE = 30.4363, INTELLECT = 55.5061, MASTERY = 33.9233, VERSATILITY = 30.9613 },
    },
    [63] = {
      profile = "MID2_Mage_Fire", dps = 226858,
      variants = { "MID2_Mage_Fire_Frostfire" },
      weights = { CRIT = 0.2357, HASTE = 0.5169, INTELLECT = 1.0000, MASTERY = 0.5416, VERSATILITY = 0.5476 },
      raw = { CRIT = 14.3372, HASTE = 31.4405, INTELLECT = 60.8198, MASTERY = 32.9370, VERSATILITY = 33.3058 },
    },
    [64] = {
      profile = "MID2_Mage_Frost", dps = 222851,
      variants = { "MID2_Mage_Frost_Frostfire" },
      weights = { CRIT = 0.5952, HASTE = 0.5540, INTELLECT = 1.0000, MASTERY = 0.5783, VERSATILITY = 0.5576 },
      raw = { CRIT = 36.5334, HASTE = 34.0036, INTELLECT = 61.3757, MASTERY = 35.4916, VERSATILITY = 34.2249 },
    },
    [66] = {
      profile = "MID2_Paladin_Protection", dps = 136498,
      variants = { "MID2_Paladin_Protection_Lightsmith" },
      weights = { CRIT = 0.6248, DPS = 5.7759, HASTE = 0.6611, MASTERY = 0.6214, STRENGTH = 1.0000, VERSATILITY = 0.6759 },
      raw = { ARMOR = -0.1857, CRIT = 21.3016, DPS = 196.9089, HASTE = 22.5381, MASTERY = 21.1847, STRENGTH = 34.0917, VERSATILITY = 23.0417 },
      error = { ARMOR = 0.8148, CRIT = 0.8219, DPS = 0.9042, HASTE = 0.8218, MASTERY = 0.8240, STRENGTH = 0.8289, VERSATILITY = 0.8211 },
    },
    [70] = {
      profile = "MID2_Paladin_Retribution", dps = 231446,
      variants = { "MID2_Paladin_Retribution_Templar" },
      weights = { CRIT = 0.6821, DPS = 5.4978, HASTE = 0.7063, MASTERY = 0.6383, STRENGTH = 1.0000, VERSATILITY = 0.5687 },
      raw = { CRIT = 38.8213, DPS = 312.8923, HASTE = 40.1971, MASTERY = 36.3256, STRENGTH = 56.9125, VERSATILITY = 32.3662 },
    },
    [71] = {
      profile = "MID2_Warrior_Arms", dps = 240755,
      weights = { CRIT = 0.7971, DPS = 5.6797, HASTE = 0.7467, MASTERY = 0.7964, STRENGTH = 1.0000, VERSATILITY = 0.7777 },
      raw = { CRIT = 42.9607, DPS = 306.1245, HASTE = 40.2463, MASTERY = 42.9225, STRENGTH = 53.8984, VERSATILITY = 41.9170 },
      error = { CRIT = 1.3958, DPS = 1.5140, HASTE = 1.3960, MASTERY = 1.4038, STRENGTH = 1.4107, VERSATILITY = 1.3968 },
    },
    [72] = {
      profile = "MID2_Warrior_Fury", dps = 256749,
      weights = { CRIT = 0.7373, DPS = 3.6347, DPS_OH = 1.3588, HASTE = 0.9671, MASTERY = 0.7656, STRENGTH = 1.0000, VERSATILITY = 0.7718 },
      raw = { CRIT = 41.9207, DPS = 206.6520, DPS_OH = 77.2536, HASTE = 54.9863, MASTERY = 43.5281, STRENGTH = 56.8549, VERSATILITY = 43.8812 },
      error = { CRIT = 1.1293, DPS = 1.1891, DPS_OH = 1.1418, HASTE = 1.1412, MASTERY = 1.1425, STRENGTH = 1.1412, VERSATILITY = 1.1446 },
    },
    [73] = {
      profile = "MID2_Warrior_Protection", dps = 155083,
      weights = { ARMOR = 0.0608, CRIT = 0.7234, DPS = 5.7893, HASTE = 0.5177, MASTERY = 0.6821, STRENGTH = 1.0000, VERSATILITY = 0.6548 },
      raw = { ARMOR = 2.1843, CRIT = 26.0017, DPS = 208.0829, HASTE = 18.6079, MASTERY = 24.5148, STRENGTH = 35.9426, VERSATILITY = 23.5352 },
      error = { ARMOR = 0.7310, CRIT = 0.7314, DPS = 0.8035, HASTE = 0.7333, MASTERY = 0.7337, STRENGTH = 0.7393, VERSATILITY = 0.7372 },
    },
    [250] = {
      profile = "MID2_Death_Knight_Blood", dps = 125103,
      variants = { "MID2_Death_Knight_Blood_Deathbringer" },
      weights = { CRIT = 0.8000, DPS = 5.1444, HASTE = 0.6291, MASTERY = 0.7504, STRENGTH = 1.0000, VERSATILITY = 0.7351 },
      raw = { ARMOR = -0.1133, CRIT = 22.9539, DPS = 147.6054, HASTE = 18.0514, MASTERY = 21.5317, STRENGTH = 28.6924, VERSATILITY = 21.0921 },
    },
    [251] = {
      profile = "MID2_Death_Knight_Frost", dps = 249921,
      variants = { "MID2_Death_Knight_Frost_Rider" },
      weights = { CRIT = 0.9012, DPS = 2.9431, DPS_OH = 0.9133, HASTE = 0.6749, MASTERY = 0.6195, STRENGTH = 1.0000, VERSATILITY = 0.4695 },
      raw = { CRIT = 62.2857, DPS = 203.4152, DPS_OH = 63.1233, HASTE = 46.6449, MASTERY = 42.8189, STRENGTH = 69.1154, VERSATILITY = 32.4484 },
      error = { CRIT = 1.4121, DPS = 1.4695, DPS_OH = 1.4102, HASTE = 1.4063, MASTERY = 1.4157, STRENGTH = 1.4227, VERSATILITY = 1.3970 },
    },
    [252] = {
      profile = "MID2_Death_Knight_Unholy", dps = 236863,
      variants = { "MID2_Death_Knight_Unholy_San'layn" },
      weights = { CRIT = 0.8973, DPS = 5.1271, HASTE = 0.7763, MASTERY = 0.6572, STRENGTH = 1.0000, VERSATILITY = 0.5548 },
      raw = { CRIT = 52.8661, DPS = 302.0757, HASTE = 45.7357, MASTERY = 38.7227, STRENGTH = 58.9176, VERSATILITY = 32.6847 },
    },
    [253] = {
      profile = "MID2_Hunter_Beast_Mastery", dps = 251114,
      weights = { AGILITY = 1.0000, CRIT = 0.6309, DPS = 5.5043, HASTE = 0.6498, MASTERY = 0.5139, VERSATILITY = 0.4605 },
      raw = { AGILITY = 65.6047, CRIT = 41.3882, DPS = 361.1076, HASTE = 42.6280, MASTERY = 33.7174, VERSATILITY = 30.2103 },
      error = { AGILITY = 1.0607, CRIT = 1.0409, DPS = 1.1562, HASTE = 1.0692, MASTERY = 1.0582, VERSATILITY = 1.0429 },
    },
    [254] = {
      profile = "MID2_Hunter_Marksmanship", dps = 239588,
      weights = { AGILITY = 1.0000, CRIT = 0.7193, DPS = 5.6187, HASTE = 0.5548, MASTERY = 0.4899, VERSATILITY = 0.4232 },
      raw = { AGILITY = 58.6438, CRIT = 42.1823, DPS = 329.5019, HASTE = 32.5352, MASTERY = 28.7310, VERSATILITY = 24.8207 },
      error = { AGILITY = 1.7280, CRIT = 1.7041, DPS = 1.8830, HASTE = 1.7231, MASTERY = 1.7105, VERSATILITY = 1.7115 },
    },
    [255] = {
      profile = "MID2_Hunter_Survival", dps = 247606,
      weights = { AGILITY = 1.0000, CRIT = 0.8335, DPS = 5.3697, HASTE = 0.9144, MASTERY = 0.6149, VERSATILITY = 0.5095 },
      raw = { AGILITY = 62.6023, CRIT = 52.1815, DPS = 336.1548, HASTE = 57.2416, MASTERY = 38.4933, VERSATILITY = 31.8953 },
      error = { AGILITY = 1.4121, CRIT = 1.3962, DPS = 1.5324, HASTE = 1.3969, MASTERY = 1.3959, VERSATILITY = 1.3922 },
    },
    [258] = {
      profile = "MID2_Priest_Shadow", dps = 208847,
      variants = { "MID2_Priest_Shadow_Archon" },
      weights = { CRIT = 0.7342, HASTE = 0.5673, INTELLECT = 1.0000, MASTERY = 0.5973, VERSATILITY = 0.6395 },
      raw = { CRIT = 41.6881, HASTE = 32.2086, INTELLECT = 56.7802, MASTERY = 33.9167, VERSATILITY = 36.3097 },
    },
    [259] = {
      profile = "MID2_Rogue_Assassination", dps = 238546,
      variants = { "MID2_Rogue_Assassination_Fatebound" },
      weights = { AGILITY = 1.0000, CRIT = 0.7488, DPS = 5.0505, DPS_OH = 0.4154, HASTE = 0.8172, MASTERY = 0.6820, VERSATILITY = 0.6663 },
      raw = { AGILITY = 60.9141, CRIT = 45.6146, DPS = 307.6491, DPS_OH = 25.3012, HASTE = 49.7771, MASTERY = 41.5461, VERSATILITY = 40.5867 },
    },
    [260] = {
      profile = "MID2_Rogue_Outlaw", dps = 256739,
      weights = { AGILITY = 1.0000, CRIT = 0.7564, DPS = 4.7362, DPS_OH = 0.8089, HASTE = 0.4928, MASTERY = 0.4238, VERSATILITY = 0.5949 },
      raw = { AGILITY = 64.8791, CRIT = 49.0744, DPS = 307.2782, DPS_OH = 52.4782, HASTE = 31.9693, MASTERY = 27.4975, VERSATILITY = 38.5943 },
      error = { AGILITY = 2.6920, CRIT = 2.6764, DPS = 2.9165, DPS_OH = 2.7165, HASTE = 2.6198, MASTERY = 2.6776, VERSATILITY = 2.6807 },
    },
    [261] = {
      profile = "MID2_Rogue_Subtlety", dps = 268187,
      weights = { AGILITY = 1.0000, CRIT = 0.5526, DPS = 5.3182, DPS_OH = 0.1980, HASTE = 0.6335, MASTERY = 0.6479, VERSATILITY = 0.6547 },
      raw = { AGILITY = 68.5266, CRIT = 37.8648, DPS = 364.4399, DPS_OH = 13.5700, HASTE = 43.4115, MASTERY = 44.3956, VERSATILITY = 44.8628 },
      error = { AGILITY = 1.1448, CRIT = 1.1328, DPS = 1.2152, DPS_OH = 1.1266, HASTE = 1.1189, MASTERY = 1.1401, VERSATILITY = 1.1412 },
    },
    [262] = {
      profile = "MID2_Shaman_Elemental", dps = 249752,
      variants = { "MID2_Shaman_Elemental_Stormbringer" },
      weights = { CRIT = 0.6911, HASTE = 0.5937, INTELLECT = 1.0000, MASTERY = 0.5656, VERSATILITY = 0.6152 },
      raw = { CRIT = 47.1500, HASTE = 40.5061, INTELLECT = 68.2289, MASTERY = 38.5888, VERSATILITY = 41.9751 },
    },
    [263] = {
      profile = "MID2_Shaman_Enhancement", dps = 234422,
      variants = { "MID2_Shaman_Enhancement_Totemic" },
      weights = { AGILITY = 1.0000, CRIT = 0.6526, DPS = 5.0348, DPS_OH = 0.4876, HASTE = 0.7086, MASTERY = 0.6968, VERSATILITY = 0.5656 },
      raw = { AGILITY = 62.1050, CRIT = 40.5328, DPS = 312.6835, DPS_OH = 30.2811, HASTE = 44.0101, MASTERY = 43.2778, VERSATILITY = 35.1293 },
    },
    [265] = {
      profile = "MID2_Warlock_Affliction", dps = 233312,
      variants = { "MID2_Warlock_Affliction_Hellcaller" },
      weights = { CRIT = 0.6291, HASTE = 0.4900, INTELLECT = 1.0000, MASTERY = 0.4639, VERSATILITY = 0.5824 },
      raw = { CRIT = 41.0953, HASTE = 32.0073, INTELLECT = 65.3224, MASTERY = 30.3053, VERSATILITY = 38.0410 },
    },
    [266] = {
      profile = "MID2_Warlock_Demonology", dps = 228947,
      weights = { CRIT = 0.6681, HASTE = 0.5031, INTELLECT = 1.0000, MASTERY = 0.5190, VERSATILITY = 0.4968 },
      raw = { CRIT = 43.0289, HASTE = 32.3993, INTELLECT = 64.4007, MASTERY = 33.4214, VERSATILITY = 31.9912 },
    },
    [267] = {
      profile = "MID2_Warlock_Destruction", dps = 228880,
      variants = { "MID2_Warlock_Destruction_Diabolist" },
      weights = { CRIT = 0.6209, HASTE = 0.5199, INTELLECT = 1.0000, MASTERY = 0.5212, VERSATILITY = 0.5106 },
      raw = { CRIT = 40.4438, HASTE = 33.8686, INTELLECT = 65.1418, MASTERY = 33.9548, VERSATILITY = 33.2595 },
    },
    [268] = {
      profile = "MID2_Monk_Brewmaster", dps = 142197,
      weights = { AGILITY = 1.0000, CRIT = 0.7433, DPS = 5.9506, HASTE = 0.2648, MASTERY = 0.5338, VERSATILITY = 0.6492 },
      raw = { AGILITY = 32.2500, ARMOR = -0.4574, CRIT = 23.9705, DPS = 191.9058, HASTE = 8.5405, MASTERY = 17.2165, VERSATILITY = 20.9361 },
      error = { AGILITY = 0.8004, ARMOR = 0.7891, CRIT = 0.8017, DPS = 0.8606, HASTE = 0.7773, MASTERY = 0.7960, VERSATILITY = 0.8003 },
    },
    [269] = {
      profile = "MID2_Monk_Windwalker", dps = 246595,
      variants = { "MID2_Monk_Windwalker_Conduit" },
      weights = { AGILITY = 1.0000, CRIT = 0.7255, DPS = 5.4934, HASTE = 0.6972, MASTERY = 0.6297, VERSATILITY = 0.5467 },
      raw = { AGILITY = 59.7780, CRIT = 43.3694, DPS = 328.3842, HASTE = 41.6793, MASTERY = 37.6450, VERSATILITY = 32.6797 },
      error = { AGILITY = 1.2744, CRIT = 1.2626, DPS = 1.3719, HASTE = 1.2606, MASTERY = 1.2671, VERSATILITY = 1.2647 },
    },
    [577] = {
      profile = "MID2_Demon_Hunter_Havoc", dps = 242249,
      variants = { "MID2_Demon_Hunter_Havoc_Aldrachi_Reaver" },
      weights = { AGILITY = 1.0000, CRIT = 0.7735, DPS = 4.7266, DPS_OH = 0.8648, HASTE = 0.5904, MASTERY = 0.5903, VERSATILITY = 0.5162 },
      raw = { AGILITY = 66.2216, CRIT = 51.2237, DPS = 313.0042, DPS_OH = 57.2684, HASTE = 39.0958, MASTERY = 39.0899, VERSATILITY = 34.1810 },
    },
    [581] = {
      profile = "MID2_Demon_Hunter_Vengeance", dps = 131400,
      weights = { AGILITY = 1.0000, ARMOR = 0.0040, CRIT = 0.7118, DPS = 5.5070, DPS_OH = 0.3576, HASTE = 0.5526, MASTERY = 0.6263, VERSATILITY = 0.6347 },
      raw = { AGILITY = 33.6308, ARMOR = 0.1356, CRIT = 23.9390, DPS = 185.2033, DPS_OH = 12.0275, HASTE = 18.5831, MASTERY = 21.0638, VERSATILITY = 21.3453 },
    },
    [1480] = {
      profile = "MID2_Demon_Hunter_Devourer", dps = 263614,
      weights = { CRIT = 0.8170, HASTE = 0.6768, INTELLECT = 1.0000, MASTERY = 0.5849, VERSATILITY = 0.5416 },
      raw = { CRIT = 57.4734, HASTE = 47.6059, INTELLECT = 70.3433, MASTERY = 41.1453, VERSATILITY = 38.0985 },
    },
  },
}
